allowBuilds:
  onnxruntime-node: set this to true or false
  protobufjs: set this to true or false
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - browserslist@4.28.5
  - caniuse-lite@1.0.30001802
  - hono@4.12.28
  - yocto-spinner@1.2.1
overrides:
  next>postcss: 8.5.16
